### ISSUE TITLE
The table always be replaced

### ISSUE THREAD

**Issue by amosricky** [favoretti/terraform-provider-adx#1]
It's a weird problem. If I follow the example to create a table with example schema ("f1:string,f2:string,f3:int"), it works fine.
However, if I change the schema (ex. "log:string,timestamp:string,xxx:int") and apply it okay and then just plan it again, it seems the table will be destroy and then create replacement. This behaviour is not make sense, the table should not be replaced if I apply it twice without any config change.

**Comment by favoretti** [comment]
Hey, sorry, missed this issue completely somehow. I'll try to reproduce and since I've seen you removed `ForceNew` in your fork, I might just do the same.

Thank you for reporting this!

**Comment by favoretti** [comment]
`v0.0.7` should address this issue.
