### ISSUE TITLE
I there a way to set the streamingingestion policy?

### ISSUE THREAD

**Issue by guy-radford-sunswap** [favoretti/terraform-provider-adx#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

v1.3.7

### ADX Provider Version

0.0.17

### Terraform Configuration Files

```hcl
resource "adx_table_update_policy" "test_update" {
  database_name = "test-db"
  table_name    = adx_table.test_update.name
  query         = adx_function.test.name
  source_table  = adx_table.test.name
  transactional = true
}
```

### Debug Output/Panic Output

```shell
N/A
```

**Comment by guy-radford-sunswap** [comment]
Apologies for raising a bug, but I couldnt find a way to ask a question.

I have searched your docs and source code and cant find any reference to enabling the `streamingingestion` policy.

This is a feature that appears to be required when linking AEX to an IoTHub.
See here for example tutorial: https://sandervandevelde.wordpress.com/2022/04/26/azure-data-explorer-connector-for-iot-hub-with-real-time-ingest/


Is this something I have missed or is not supported?

Thank you

**Comment by favoretti** [comment]
@guy-radford-sunswap Thank you for raising this issue. Not a problem that it's a question, we don't have a separation between those yet, since flow of issues is low luckily :) I think this is not supported yet though. @slwbuild am I correct here?

**Comment by slwbuild** [comment]
Sorry for the really slow response. This feature is not yet supported but looks somewhat easy to add and I will put it in our internal backlog. No ETA just yet due to other priorities I'm afraid.

**Comment by guy-radford-sunswap** [comment]
Hi @slwbuild, not a problem we are all busy :) Thank you for your reply and confirming that  I hadnt missed anything. Definitely a useful feature when connecting to IoTHub. For the moment I will find a work round.
Thank you

**Comment by slwbuild** [comment]
Working on this enhancement now. Should release with v0.0.18 soon.

**Comment by guy-radford-sunswap** [comment]
Thank you, I will try and give it ago today.
