### ISSUE TITLE
plugin crash - after failure to delete kusto tables

### ISSUE THREAD

**Issue by kiranpradeep** [favoretti/terraform-provider-adx#3]
I am pasting the screenshot here as it was suggested to do so after the error. The below code created the adx tables initially. I also had terraform script to create adx cluster/db/admin principal as in [example](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_database_principal_assignment).

 This error started happening when I changed the name of adx DB. For that the kusto tables and admin prinicpal  (created by `azurerm_kusto_database_principal_assignment` for client id/secret used below) had to be deleted and recreated in order. I assume that the admin principal used in below hcl got deleted first before the tables got deleted. So terraform could not delete the tables. I feel like this provider is not ordering actions correctly.

You will be able to reproduce this error if you change the name of adx DB to get the out of order error mentioned above. Later I manually added the admin principal to adx (using Azure portal) and plugin started crashing.

I feel hashicorp/terraform-provider-azurerm#6392 should be left open as there are ordering issues with this provider.

```hcl
terraform {
  required_providers {
    adx = {
      source = "favoretti/adx"
    }
  }
}

# Configure the Azure Data Explorer provider
provider "adx" {
  adx_endpoint    = "..."
  client_id       = "..."
  client_secret   = "..."
  tenant_id       = "..."
}

resource "adx_table" "test" {
  name          = "Test1"
  database_name = "test-db"

  # either
  table_schema  = "f1:string,f2:string,f3:int"
}
```

![image](https://user-images.githubusercontent.com/1491933/143461787-33ebbc65-a8c7-4062-8242-dfbabbf295b6.png)

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I'm hoping to have addressed this particular crash in v0.0.9, however the ordering issues are out of my power. Terraform deduces what goes first and what goes next, you can influence that yourself by using `depends_on`, but there's very little I can do from this provider's standpoint.

**Comment by kiranpradeep** [comment]
Thanks @favoretti for the reply. I will verify the crash again. 

More importantly, should not hashicorp/terraform-provider-azurerm#6392 be reopened? In that ticket it was to be considered again in future. It was becuase of this existence of this provider that the popular feature requested was closed. But this provider as you said is not really solving the case.

**Comment by favoretti** [comment]
It's up to the maintainers, but since we usually do not use non-ARM APIs in azurerm provider - chances are slim that it will make it in there. Feel free to bring this topic up on slack though. 

Looking at the fact that this provider had over 2k installs though - I guess it solves at least something :)
