### ISSUE TITLE
adx_table: Column always wants to be updated.

### ISSUE THREAD

**Issue by guy-radford-sunswap** [favoretti/terraform-provider-adx#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

v1.3.7

### ADX Provider Version

v0.0.18

### Terraform Configuration Files

```hcl
resource "adx_table" "events" {
  name          = "events"
  database_name = local.axd_database_name

  #.create table events (
  #    event_id: string,
  #    event_timestamp: datetime,
  #    event_enqueuedtime: datetime,
  #    device_id: string,
  #    event_name: string,
  #    version:int,
  #    payload: dynamic
  #)

  column {
    name = "event_id"
    type = "string"
  }
  column {
    name = "event_timestamp"
    type = "datetime"
  }
  column {
    name = "event_write_timestamp"
    type = "datetime"
  }
  column {
    name = "device_id"
    type = "string"
  }
  column {
    name = "event_name"
    type = "string"
  }
  column {
    name = "version"
    type = "int"
  }
  column {
    name = "payload"
    type = "dynamic"
  }
  depends_on = [adx_table.iothub_received_raw_events]
}
```

### Debug Output/Panic Output

```shell
# adx_table.events will be updated in-place
  ~ resource "adx_table" "events" {
        id              = "adxedrdevuksouth.uksouth.kusto.windows.net|adxdb-endurance-dev-uksouth|table|events"
        name            = "events"
        # (3 unchanged attributes hidden)

      ~ column {
          ~ name = "['version']" -> "version"
            # (1 unchanged attribute hidden)
        }

        # (6 unchanged blocks hidden)
    }
```

### Expected Behaviour

I would expect the version field to not require changing, this has not chnage since a complete re-build.

### Actual Behaviour

TF suggest the `version` field needs updating, even when it does not.

Thank you

**Comment by slwbuild** [comment]
We see this one internally a lot. I just haven't gotten around to fixing it (By using some hacky DiffSupression). Essentially the escaping is automatically removed by ADX if not needed for characters like '-' and state is updated accordingly which causes the change on next plan.

**Comment by slwbuild** [comment]
Looking at it again, it actually seems to be the reverse problem. `version` might be a type of keyword in ADX and it's trying to escape it for you. Some more research is obviously required for this one (DiffSupression still might fix).

**Comment by slwbuild** [comment]
ADX allows you to name a column basically anything as long as its escaped. I haven't figured out an elegant solution just yet.

**Comment by favoretti** [comment]
Normalize everything to escaped form during read and in the state?

**Comment by slwbuild** [comment]
Yeah I was thinking we just add a diff suppression function on the name where we perform the following:

* If new val/config is escaped, make sure we compare against an escaped(old val)...If match, suppress 
* If new val/config is not escaped, make sure escaping is stripped from old val...If match, suppress

**Comment by slwbuild** [comment]
Nearly finished with this one. When i added a few acceptance tests to reproduce the above I found some additional bugs related to adding new columns to an existing table (they aren't added properly).

**Comment by guy-radford-sunswap** [comment]
> @guy-radford-sunswap if you rename the column from `version` to something else - does the effect persist? Also, if `version` is a keyword - do we want to prohibit columns with that name or kludge around it?

Ill give it ago when I next to a rebuild, probably wont be today...sorry I missed this the other day.
