### ISSUE TITLE
adx_materialized_view add Materialzed view but errors after.

### ISSUE THREAD

**Issue by guy-radford-sunswap** [favoretti/terraform-provider-adx#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

v1.3.7

### ADX Provider Version

v0.0.19

### Terraform Configuration Files

```hcl
resource "adx_materialized_view" "devices" {
  name              = "devices"
  database_name     = local.axd_database_name
  source_table_name = adx_table.events.name
  backfill          = true
  async             = true
  query             = "events | summarize  min(event_timestamp), max(event_write_timestamp) by device_id"
}
```

### Debug Output/Panic Output

```shell
adx_materialized_view.devices: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to adx_materialized_view.devices, provider "provider[\"registry.terraform.io/favoretti/adx\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Expected Behaviour

No Error

### Actual Behaviour

On Create

1. Creates MV
2. TR Output shows Error `Root resource was present, but now absent.`
3. MV is in ADX and is working

Re-runs work fine, no error and MV still fine.

**Comment by guy-radford-sunswap** [comment]
Works fine with the following removed:
```
  backfill          = true
  async             = true
```

**Comment by slwbuild** [comment]
Thanks for opening this one. I think the main issue here is that the provider does not currently handle async tasks. 

It expects (regardless of async flag) that the resource is immediately created once the API response is received.
It then runs a `.show` command to get the view details and doesn't get what it expects.

For any ADX resource which has an async option it will need to receive the `OperationId` from the creation API call and poll ADX until success/failure before proceeding. Many other providers do this (such as azurerm).

**Comment by guy-radford-sunswap** [comment]
That makes sense from what i am learning about ADX for the MV's.
