### ISSUE TITLE
Missing terraform docs desciption text for update policy source_table argument

### ISSUE THREAD

**Issue by FakieHeelflip** [favoretti/terraform-provider-adx#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

1.3.7

### ADX Provider Version

0.0.19

### Terraform Configuration Files

```hcl
In the adx_table_update_policy.md is the description text for the source_table missing.
```

### Debug Output/Panic Output

```shell
/
```

### Expected Behaviour

`- **source_table** (String, Required) Name of the table that represents the source for the update policy`

**Comment by FakieHeelflip** [comment]
I am not able to raise a pull request for those little things so maybe there is an option to contribute in the future. :) Diving deeper into the code.

**Comment by slwbuild** [comment]
I'm happy to fix the doc issue if you would like.

If you would like to contribute please follow these steps to get started:

https://github.com/firstcontributions/first-contributions

**Comment by FakieHeelflip** [comment]
@slwbuild done.
