### ISSUE TITLE
Add arguments to function inside update policy or row level security

### ISSUE THREAD

**Issue by FakieHeelflip** [favoretti/terraform-provider-adx#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

1.3.7

### ADX Provider Version

0.0.19

### Terraform Configuration Files

```hcl
A trivial example to get the concept:


resource "adx_function" "rls_function" {

  database_name = "test-db"
  name          = "my-rls-func"
  body          = "{table_var | limit 10}"
  parameters    = "(table_var:string)"
}


resource "adx_table_row_level_security_policy" "rls_policy" {
  database_name = "test-db"
  table_name    = "test-table"
  query         = "my-rls-func"
  query_args    = "(table_var:test-table)"
  enabled       = true
}

... the same for update policy and everywhere where functions are called.
```

### Debug Output/Panic Output

```shell
/
```

**Comment by FakieHeelflip** [comment]
If you do not mind I would try to implement it, but I am not sure wether we should validate the args against the given params in the function on our side or just concatenate it to the kusto string?

**Comment by slwbuild** [comment]
I may be misunderstanding, but can't you just place the parameters in the query attribute itself? It accepts more than a function name: 

```hcl
resource "adx_table_row_level_security_policy" "rls_policy" {
  database_name = "test-db"
  table_name        = "test-table"
  query                  = "my-rls-func(table_var:test-table)"
  enabled              = true
}
```

**Comment by FakieHeelflip** [comment]
Oh yes, you are right. Excuse me for that.
