### ISSUE TITLE
Missing option - ingestiontime

### ISSUE THREAD

**Issue by jpoizat** [favoretti/terraform-provider-adx#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

1.4.6

### ADX Provider Version

0.0.22

### Terraform Configuration Files

```hcl
any configuration would work (not really an issue, but an enhancement)
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

expecting to be able to configure ingestiontime option
ref : 
https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-ingestion-time-policy-command
command in Kusto:
.alter table <tablename> policy ingestiontime true

### Actual Behaviour

ingestiontime configured in table policy

**Comment by FakieHeelflip** [comment]
Hi @jpoizat , I add the ingestion time ressource and made a pull request. Hopefully it will be in the provider within a few days after the review. Stay tuned and thank you for raising an issue.

**Comment by jpoizat** [comment]
Greaty @FakieHeelflip
thanks a lot !

**Comment by favoretti** [comment]
Closing this one as resolved.
